export const POST_CARD_USERS = 'POST_CARD_USERS';
export const  POST_PUT_CARD_USERS = 'POST_PUT_CARD_USERS';
export const GET_CURRENT_ID = 'GET_CURRENT_ID';
export const CURRENT_TITLE_NAVBAR = 'CURRENT_TITLE_NAVBAR';